using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class D_UserData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new D_UserData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new D_UserData(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "UserData";
		public const string name = "name";
		public const string Gold = "Gold";
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4904133964773069639UL,16850384506740578441UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public System.Int32 f_Gold
	{
		get => _f_Gold[Index];
		set => _f_Gold[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5099075977080668416UL, 16473470366231641492UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Gold;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Gold => _ufle12jhs77_f_Gold ?? (_ufle12jhs77_f_Gold = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5241885685379121128UL, 1145151766458729353UL), () => _ufle12jhs77_f_Gold = null));
	private static readonly D_UserData.Factory _factory0_PFS = new D_UserData.Factory();
	private D_UserData() : base(MetaDefault) {}
	private D_UserData(BGId id) : base(MetaDefault, id) {}
	private D_UserData(BGMetaEntity meta) : base(meta) {}
	private D_UserData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static D_UserData FindEntity(Predicate<D_UserData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<D_UserData> FindEntities(Predicate<D_UserData> filter, List<D_UserData> result=null, Comparison<D_UserData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<D_UserData> action, Predicate<D_UserData> filter=null, Comparison<D_UserData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static D_UserData GetEntity(BGId entityId) => (D_UserData) MetaDefault.GetEntity(entityId);
	public static D_UserData GetEntity(int index) => (D_UserData) MetaDefault[index];
	public static D_UserData GetEntity(string entityName) => (D_UserData) MetaDefault.GetEntity(entityName);
	public static D_UserData NewEntity() => (D_UserData) MetaDefault.NewEntity();
	public static D_UserData NewEntity(BGId entityId) => (D_UserData) MetaDefault.NewEntity(entityId);
	public static D_UserData NewEntity(Action<D_UserData> callback) => (D_UserData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((D_UserData)entity)));
}
#pragma warning restore 414
